[package]
name = "routefilterd"
version = "0.1.0"
edition = "2024"

[dependencies]
async-compression = { version = "0.4.41", features = ["gzip", "tokio"] }
async-stream = "0.3.6"
axum = { version = "0.8", default-features = false, features = ["query", "http1", "tokio"] }
file_type = "0.8.11"
flate2 = "1.1.5"
futures-util = "0.3.31"
http = "1.3.1"
log = "0.4.28"
nrtm-parser = { version = "0.1.0", features = ["async-streaming"] }
phf = "0.14.0"
phf_macros = "0.14.0"
regex = "1.11.2"
reqwest = { version = "0.13.1", features = ["stream"] }
rpsl-rs = "2.0.1"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
suppaftp = { version = "^8", features = ["async-secure", "tokio"] }
thiserror = "2.0.18"
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["io"] }
toml = "0.9.8"

[dev-dependencies]
const_format = "0.2.36"
libunftp = "0.23.0"
openport = { version = "0.4.0", features = ["rand"] }
stringreader = "0.1.1"
tempfile = "3.27.0"
unftp-core = "0.1.0"
unftp-sbe-fs = "0.4.0"
wiremock = "0.6.5"
