log_level = "debug"

[api]
listen_address = "[::]:1337"

[data_sources.RIPE]
import_sources = ["data/ripe.db"]
import_serial = "https://ftp.ripe.net/ripe/dbase/RIPE.CURRENTSERIAL"
nrtm_address = "whois.ripe.net:4444"
priority = 500

[data_sources.ARIN]
import_sources = ["data/arin.db"]
priority = 400

[data_sources.RADB]
import_sources = ["data/radb.db"]
priority = 200

[data_sources.NTTCOM]
import_sources = ["data/nttcom.db"]
priority = 250

[data_sources.IDNIC]
import_sources = ["data/idnic.db"]
priority = 150

[data_sources.LACNIC]
import_sources = ["data/lacnic.db"]
priority = 150

[data_sources.APNIC]
import_sources = [
  "data/apnic.db.as-set",
  "data/apnic.db.route",
  "data/apnic.db.route6",
]
priority = 400

[data_sources.TC]
import_sources = ["data/tc.db"]
priority = 150

[data_sources.LEVEL3]
import_sources = ["data/level3.db"]
priority = 150

[data_sources.JPIRR]
import_sources = ["data/jpirr.db"]
priority = 150

[data_sources.BBOI]
import_sources = ["data/bboi.db"]
priority = 150

[data_sources.BELL]
import_sources = ["data/bell.db"]
priority = 150

[data_sources.AFRINIC]
import_sources = ["data/afrinic.db"]
priority = 200

