[api]
listen_address = "[::]:1337"

[data_sources.RIPE]
import_sources = ["data/ripe.db"]
import_serial = "https://ftp.ripe.net/ripe/dbase/RIPE.CURRENTSERIAL"
nrtm_address = "whois.ripe.net:4444"
priority = 500

[data_sources.ARIN]
import_sources = ["data/arin.db"]
priority = 400
