name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: show tooling versions
      run: |
        cargo -V
        cargo fmt -- -V
        cargo clippy -V
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: actions/cache@v5
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - name: check formatting
      run: cargo fmt -v --check
    - name: check linting
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: run tests and report coverage
      run: cargo llvm-cov
