name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v5
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - uses: actions/checkout@v4
    - name: check formatting
      run: cargo fmt -v --check
    - name: run tests
      run: cargo test --verbose
